### ISSUE TITLE
Problems with more than 15 digits

### ISSUE THREAD

**Issue by gpedro** [alvarowolfx/ng-keypad#1]
the correct behavior when entering more digits that fit the screen is to continue showing the last right.

incorrect
![captura de tela 2015-06-03 as 01 49 44](https://cloud.githubusercontent.com/assets/2898638/7953446/d9b037f2-0992-11e5-89ea-13d38c7b3822.png)

correct
![captura de tela 2015-06-03 as 01 49 48](https://cloud.githubusercontent.com/assets/2898638/7953447/d9b17c02-0992-11e5-8159-5b09a739bd04.png)

**Comment by alvarowolfx** [comment]
Any clue on how to resolve this ?
